CREATE TABLE passkey_credentials
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            BIGINT NOT NULL,
    label              VARCHAR(255),
    credential_type    VARCHAR(255),
    credential_id      VARCHAR(255),
    public_key_cose    VARCHAR(255),
    signature_count    BIGINT,
    uv_initialized     BOOLEAN,
    transports         VARCHAR(255),
    backup_eligible    BOOLEAN,
    backup_state       BOOLEAN,
    attestation_object VARCHAR(255),
    last_used          TIMESTAMP WITHOUT TIME ZONE,
    created            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_passkey_credentials PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role    VARCHAR(255)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(255) NOT NULL,
    password     VARCHAR(255),
    external_id  VARCHAR(255),
    display_name VARCHAR(255),
    enabled      BOOLEAN,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE passkey_credentials
    ADD CONSTRAINT FK_PASSKEY_CREDENTIALS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);
